spring:
  datasource:
    url: jdbc:sqlserver://assurancemilitaire.database.windows.net:1433;database=assurancemilitaire;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: youssef
    password: Assurance123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect